[package]
name = "neuton-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "neuton"
path = "src/main.rs"

[dependencies]
neuton-protocol = { workspace = true }
neuton-blocks = { workspace = true }
neuton-auth = { path = "../neuton-auth" }
neuton-net = { path = "../neuton-net" }
neuton-world = { path = "../neuton-world" }
neuton-ui = { path = "../neuton-ui" }
neuton-render = { version = "0.1.0", path = "../neuton-render" }
