[package]
name = "neuton-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neuton-auth = { path = "../neuton-auth" }
egui = "0.36.1"
egui-wgpu = "0.36.1"
egui-winit = "0.36.1"
pollster = "1.0.1"
wgpu = "30.0.1"
winit = "0.30.13"
png = "0.18.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
neuton-net = { version = "0.1.0", path = "../neuton-net" }
neuton-protocol = { version = "0.1.0", path = "../neuton-protocol" }
