[package]
name = "neuton-net"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neuton-protocol = { workspace = true }
neuton-blocks = { workspace = true }
neuton-world = { path = "../neuton-world" }
neuton-nbt = { path = "../neuton-nbt" }
neuton-auth = { path = "../neuton-auth" }
serde_json = "1.0.151"
