//! Generates `neuton-blocks` from `reports/blocks.json`.
//!
//! Chunk sections arrive as palettes of *global block state IDs*. Turning those
//! back into blocks is the single hottest lookup in chunk meshing, so the
//! generated table is a flat array indexed directly by state ID rather than a
//! map.

use crate::{Ctx, const_name, emit};
use std::fmt::Write as _;

pub fn generate(ctx: &Ctx) -> Result<(), Box<dyn std::error::Error>> {
    let raw = std::fs::read_to_string(ctx.reports.join("blocks.json"))?;
    let doc: serde_json::Map<String, serde_json::Value> = serde_json::from_str(&raw)?;

    struct Block {
        name: String,
        first_state: u32,
        state_count: u32,
        default_state: u32,
    }

    let mut blocks = Vec::with_capacity(doc.len());
    let mut state_count = 0usize;

    for (name, value) in &doc {
        let states = value.get("states").and_then(|s| s.as_array()).ok_or("block with no states")?;
        let mut ids: Vec<u32> = states
            .iter()
            .filter_map(|s| s.get("id")?.as_u64().map(|v| v as u32))
            .collect();
        ids.sort_unstable();

        // Vanilla allocates every block's states consecutively. The flat lookup
        // table below depends on that, so verify rather than assume.
        if let (Some(&first), Some(&last)) = (ids.first(), ids.last())
            && last - first + 1 != ids.len() as u32
        {
            return Err(format!("block {name} has non-contiguous state ids").into());
        }

        let default_state = states
            .iter()
            .find(|s| s.get("default").and_then(|d| d.as_bool()).unwrap_or(false))
            .or_else(|| states.first())
            .and_then(|s| s.get("id")?.as_u64())
            .ok_or("block with no default state")? as u32;

        state_count += ids.len();
        blocks.push(Block {
            name: name.clone(),
            first_state: *ids.first().ok_or("block with zero states")?,
            state_count: ids.len() as u32,
            default_state,
        });
    }

    // Order by first state id so block index and state id rise together.
    blocks.sort_by_key(|b| b.first_state);

    let max_state = blocks.iter().map(|b| b.first_state + b.state_count).max().unwrap_or(0) as usize;
    if max_state != state_count {
        return Err(format!("state ids are not dense: {max_state} slots for {state_count} states").into());
    }
    if blocks.len() > u16::MAX as usize {
        return Err("more blocks than a u16 block index can address".into());
    }

    let mut out = String::with_capacity(1024 * 1024);
    writeln!(out, "// @generated by neuton-datagen from vanilla {} reports/blocks.json", ctx.version)?;
    writeln!(out, "// Do not edit. Run `cargo run -p neuton-datagen` to regenerate.")?;
    writeln!(out, "#![allow(dead_code)]\n")?;
    writeln!(out, "use crate::{{Block, BlockId, StateId}};\n")?;
    writeln!(out, "pub const BLOCK_COUNT: usize = {};", blocks.len())?;
    writeln!(out, "/// Total distinct block states; valid state IDs are `0..STATE_COUNT`.")?;
    writeln!(out, "pub const STATE_COUNT: usize = {state_count};\n")?;

    writeln!(out, "pub static BLOCKS: [Block; BLOCK_COUNT] = [")?;
    for b in &blocks {
        writeln!(
            out,
            "    Block {{ name: {:?}, first_state: StateId({}), state_count: {}, default_state: StateId({}) }},",
            b.name, b.first_state, b.state_count, b.default_state
        )?;
    }
    writeln!(out, "];\n")?;

    // Flat state -> block index. ~64 KiB of .rodata buys an O(1) lookup on the
    // meshing hot path, versus a binary search per block in every chunk.
    let mut state_to_block = vec![0u16; state_count];
    for (idx, b) in blocks.iter().enumerate() {
        for s in b.first_state..b.first_state + b.state_count {
            state_to_block[s as usize] = idx as u16;
        }
    }
    writeln!(out, "/// Block index for every global state ID, for O(1) palette decoding.")?;
    writeln!(out, "pub static STATE_TO_BLOCK: [u16; STATE_COUNT] = [")?;
    for chunk in state_to_block.chunks(32) {
        let line: Vec<String> = chunk.iter().map(u16::to_string).collect();
        writeln!(out, "    {},", line.join(","))?;
    }
    writeln!(out, "];\n")?;

    writeln!(out, "/// Block indices by name, for code that needs to name a block.")?;
    writeln!(out, "pub mod block {{")?;
    writeln!(out, "    use super::BlockId;")?;
    for (idx, b) in blocks.iter().enumerate() {
        writeln!(out, "    /// `{}`", b.name)?;
        writeln!(out, "    pub const {}: BlockId = BlockId({idx});", const_name(&b.name))?;
    }
    writeln!(out, "}}")?;

    let path = ctx.repo.join("crates/neuton-blocks/src/generated/blocks.rs");
    emit(&path, &out)?;
    println!("  blocks        : {} blocks, {state_count} states", blocks.len());
    Ok(())
}
