//! Entity types and the size of the box each one occupies.
//!
//! Registry order is wire order, so the index into this table is the id the
//! add-entity packet carries. The sizes are not decoration: the box is what a
//! hit has to land in, so a client that guesses one guesses the reach it gives
//! the player.

use crate::{Ctx, emit};
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

type Err = Box<dyn std::error::Error>;

pub fn generate(ctx: &Ctx, java: &Path, classpath: &str) -> Result<(), Err> {
    let source = ctx.repo.join("crates/neuton-datagen/java/DumpEntities.java");
    let classes = ctx.repo.join("target/datagen/classes");
    std::fs::create_dir_all(&classes)?;

    let javac = java.with_file_name("javac");
    let status = Command::new(&javac)
        .args(["-nowarn", "-cp", classpath, "-d"])
        .arg(&classes)
        .arg(&source)
        .status()?;
    if !status.success() {
        return Err(format!("compiling {} failed", source.display()).into());
    }

    let separator = if cfg!(windows) { ';' } else { ':' };
    let dumped = ctx.repo.join("target/datagen/entities.json");
    let status = Command::new(java)
        .arg("-XX:+UseSerialGC")
        .arg("-cp")
        .arg(format!("{}{separator}{classpath}", classes.display()))
        .arg("DumpEntities")
        .arg(&dumped)
        .stdout(std::process::Stdio::null())
        .status()?;
    if !status.success() {
        return Err("the entity extractor failed".into());
    }
    let entries: Vec<serde_json::Value> =
        serde_json::from_str(&std::fs::read_to_string(&dumped)?)?;

    let mut rows = vec![("minecraft:pig".to_string(), 0.0f32, 0.0f32, 0.0f32); entries.len()];
    for entry in &entries {
        let id = entry["id"].as_u64().ok_or("entry with no id")? as usize;
        if id >= rows.len() {
            return Err("entity id out of range".into());
        }
        rows[id] = (
            entry["name"].as_str().unwrap_or_default().to_string(),
            entry["width"].as_f64().unwrap_or(0.0) as f32,
            entry["height"].as_f64().unwrap_or(0.0) as f32,
            entry["eye"].as_f64().unwrap_or(0.0) as f32,
        );
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by neuton-datagen from the vanilla {} jar\n\
         // Do not edit. Run `cargo run -p neuton-datagen` to regenerate.\n\
         //!\n\
         //! Every entity type, in registry order, which is the order the wire\n\
         //! uses: the index here is the id an add-entity packet carries.\n\
         #![allow(dead_code)]\n\
         \n\
         /// One entity type, and the box it stands in.\n\
         #[derive(Debug, Clone, Copy, PartialEq)]\n\
         pub struct EntityKind {{\n\
         \x20   pub name: &'static str,\n\
         \x20   /// The box is this wide on both horizontal axes.\n\
         \x20   pub width: f32,\n\
         \x20   pub height: f32,\n\
         \x20   /// How far above the feet the eyes sit.\n\
         \x20   pub eye_height: f32,\n\
         }}\n\
         \n\
         pub const ENTITY_KIND_COUNT: usize = {};\n",
        ctx.version,
        rows.len()
    );

    let _ = writeln!(out, "pub static ENTITY_KINDS: [EntityKind; ENTITY_KIND_COUNT] = [");
    for (name, width, height, eye) in &rows {
        let _ = writeln!(
            out,
            "    EntityKind {{ name: {name:?}, width: {width:?}, height: {height:?}, eye_height: {eye:?} }},"
        );
    }
    let _ = writeln!(out, "];");

    let _ = writeln!(
        out,
        "\n/// The type an add-entity packet named, or `None` for an id from a\n\
         /// server that knows an entity this build does not.\n\
         #[inline]\n\
         pub fn kind(id: i32) -> Option<&'static EntityKind> {{\n\
         \x20   usize::try_from(id).ok().and_then(|id| ENTITY_KINDS.get(id))\n\
         }}"
    );

    emit(&ctx.repo.join("crates/neuton-world/src/generated/entities.rs"), &out)?;
    println!("  entities      : {} types", rows.len());
    Ok(())
}
