//! Entity geometry, extracted from the client jar.
//!
//! No file in the assets describes the shape of a zombie: entity models are
//! built in code, as a tree of named parts holding boxes. The client builds
//! every one of them in a single call, which is what makes them extractable,
//! and the same call covers block entities, so chests and signs come out of it
//! too.
//!
//! What cannot come out of it is animation. How a part moves is a method per
//! model, and that stays on our side.

use crate::{Ctx, emit};
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

type Err = Box<dyn std::error::Error>;

pub fn generate(ctx: &Ctx, java: &Path, classpath: &str) -> Result<(), Err> {
    let source = ctx.repo.join("crates/neuton-datagen/java/DumpEntityModels.java");
    let classes = ctx.repo.join("target/datagen/classes");
    std::fs::create_dir_all(&classes)?;

    let javac = java.with_file_name("javac");
    let status = Command::new(&javac)
        .args(["-nowarn", "-cp", classpath, "-d"])
        .arg(&classes)
        .arg(&source)
        .status()?;
    if !status.success() {
        return Err(format!("compiling {} failed", source.display()).into());
    }

    let separator = if cfg!(windows) { ';' } else { ':' };
    let dumped = ctx.repo.join("target/datagen/entity_models.json");
    let status = Command::new(java)
        .arg("-XX:+UseSerialGC")
        .arg("-cp")
        .arg(format!("{}{separator}{classpath}", classes.display()))
        .arg("DumpEntityModels")
        .arg(&dumped)
        .arg(ctx.jar.as_os_str())
        .stdout(std::process::Stdio::null())
        .status()?;
    if !status.success() {
        return Err("the entity model extractor failed".into());
    }

    let document: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&dumped)?)?;
    let models = document["models"].as_object().ok_or("expected an object of layers")?;
    let looks = document["looks"].as_object().ok_or("expected a lookup table")?;

    let mut out = String::new();
    out.push_str(
        "//! Entity and block entity models, generated by neuton-datagen.\n\
         //!\n\
         //! Do not edit. The shapes are the client's own, read out of the jar: a\n\
         //! tree of parts, each part posed relative to its parent and holding boxes\n\
         //! measured in texture pixels with the part's origin at zero.\n\n",
    );
    out.push_str(
        "/// One box of a model, in the sixteen-to-a-block units a skin is drawn in.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct Cube {\n\
         \x20   /// The corner the box grows from, before `grow` is applied.\n\
         \x20   pub at: [f32; 3],\n\
         \x20   pub size: [f32; 3],\n\
         \x20   /// Pushed out on every side, for a second layer that has to sit\n\
         \x20   /// clear of the first without being a different shape.\n\
         \x20   pub grow: [f32; 3],\n\
         \x20   /// Top left of this box's unfolding on the texture, in pixels.\n\
         \x20   pub uv: [f32; 2],\n\
         \x20   /// How many texture pixels one model unit takes, per axis.\n\
         \x20   pub uv_scale: [f32; 2],\n\
         \x20   /// Drawn with its texture flipped, so one side of a skin can serve\n\
         \x20   /// both arms.\n\
         \x20   pub mirror: bool,\n\
         }\n\n\
         /// A named piece of a model, posed relative to whatever holds it.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct Part {\n\
         \x20   pub name: &'static str,\n\
         \x20   /// Offset then rotation then scale: x, y, z, then radians about\n\
         \x20   /// each axis, then a scale per axis.\n\
         \x20   pub pose: [f32; 9],\n\
         \x20   pub cubes: &'static [Cube],\n\
         \x20   pub children: &'static [Part],\n\
         }\n\n\
         /// One layer of one model: what the client calls `entity#main`.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct Model {\n\
         \x20   pub key: &'static str,\n\
         \x20   /// The texture this geometry unfolds onto, in pixels.\n\
         \x20   pub texture_size: [f32; 2],\n\
         \x20   pub root: Part,\n\
         }\n\n",
    );

    let mut count = 0;
    writeln!(out, "pub static MODELS: &[Model] = &[")?;
    for (key, model) in models {
        let size = model["texture_size"].as_array().ok_or("texture_size")?;
        writeln!(out, "    Model {{")?;
        writeln!(out, "        key: {key:?},")?;
        writeln!(
            out,
            "        texture_size: [{}.0, {}.0],",
            size[0].as_i64().unwrap_or(64),
            size[1].as_i64().unwrap_or(64)
        )?;
        out.push_str("        root: ");
        part(&mut out, "root", &model["root"], 2)?;
        out.push_str(",\n    },\n");
        count += 1;
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// The model for a layer key, such as `minecraft:zombie#main`.\n\
         pub fn model(key: &str) -> Option<&'static Model> {\n\
         \x20   MODELS.iter().find(|m| m.key == key)\n\
         }\n\n\
         /// What a kind of entity is drawn as: its model, and the texture that\n\
         /// model unfolds onto, relative to `assets/minecraft/textures`.\n\
         ///\n\
         /// Only the kinds the client models this way. A falling block, an\n\
         /// arrow's trail or an experience orb is drawn some other way, and is\n\
         /// absent here rather than wrong.\n\
         pub static LOOKS: &[(&str, &str, &str)] = &[\n",
    );
    let mut looks_count = 0;
    for (kind, look) in looks {
        writeln!(
            out,
            "    ({kind:?}, {:?}, {:?}),",
            look["model"].as_str().unwrap_or_default(),
            look["texture"].as_str().unwrap_or_default(),
        )?;
        looks_count += 1;
    }
    out.push_str(
        "];\n\n\
         /// The model and texture for an entity kind, such as `minecraft:cow`.\n\
         pub fn look(kind: &str) -> Option<(&'static Model, &'static str)> {\n\
         \x20   let (_, key, texture) = LOOKS.iter().find(|(name, ..)| *name == kind)?;\n\
         \x20   Some((model(key)?, texture))\n\
         }\n",
    );

    emit(&ctx.repo.join("crates/neuton-render/src/generated/entity_models.rs"), &out)?;
    println!("  entity models : {count} layers, {looks_count} kinds drawn");
    Ok(())
}

/// Writes one part and everything under it.
fn part(out: &mut String, name: &str, value: &serde_json::Value, depth: usize) -> Result<(), Err> {
    let pad = "    ".repeat(depth);
    let number = |v: &serde_json::Value| -> String {
        let f = v.as_f64().unwrap_or(0.0) as f32;
        if f == f.trunc() && f.abs() < 1.0e7 { format!("{f:.1}") } else { format!("{f:?}") }
    };

    writeln!(out, "Part {{")?;
    writeln!(out, "{pad}    name: {name:?},")?;
    let pose = value["pose"].as_array().ok_or("pose")?;
    let pose: Vec<String> = pose.iter().map(number).collect();
    writeln!(out, "{pad}    pose: [{}],", pose.join(", "))?;

    let cubes = value["cubes"].as_array().ok_or("cubes")?;
    if cubes.is_empty() {
        writeln!(out, "{pad}    cubes: &[],")?;
    } else {
        writeln!(out, "{pad}    cubes: &[")?;
        for cube in cubes {
            let three = |k: &str| -> String {
                cube[k]
                    .as_array()
                    .map(|a| a.iter().map(number).collect::<Vec<_>>().join(", "))
                    .unwrap_or_else(|| "0.0, 0.0, 0.0".to_string())
            };
            writeln!(
                out,
                "{pad}        Cube {{ at: [{}], size: [{}], grow: [{}], uv: [{}], uv_scale: [{}], mirror: {} }},",
                three("at"),
                three("size"),
                three("grow"),
                three("uv"),
                three("uv_scale"),
                cube["mirror"].as_bool().unwrap_or(false),
            )?;
        }
        writeln!(out, "{pad}    ],")?;
    }

    let children = value["children"].as_object().ok_or("children")?;
    if children.is_empty() {
        writeln!(out, "{pad}    children: &[],")?;
    } else {
        writeln!(out, "{pad}    children: &[")?;
        for (child_name, child) in children {
            out.push_str(&format!("{pad}        "));
            part(out, child_name, child, depth + 2)?;
            out.push_str(",\n");
        }
        writeln!(out, "{pad}    ],")?;
    }
    write!(out, "{pad}}}")?;
    Ok(())
}
