//! Generates the item and data-component tables from `reports/registries.json`.
//!
//! Item stacks arrive as a protocol ID and a list of components, both of which
//! are registry indices. Turning those back into names needs the same table the
//! server used, which the vanilla generator will simply hand over.

use crate::{Ctx, emit};
use std::fmt::Write as _;

/// Reads a registry into a vector indexed by protocol ID.
fn registry(doc: &serde_json::Value, name: &str) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let entries = doc
        .get(name)
        .and_then(|r| r.get("entries"))
        .and_then(|e| e.as_object())
        .ok_or_else(|| format!("no {name} registry"))?;
    let mut out = vec![String::new(); entries.len()];
    for (key, value) in entries {
        let id = value.get("protocol_id").and_then(|v| v.as_u64()).ok_or("entry with no id")?;
        let key = key.strip_prefix("minecraft:").unwrap_or(key);
        *out.get_mut(id as usize).ok_or("registry id out of range")? = key.to_string();
    }
    Ok(out)
}

pub fn generate(ctx: &Ctx) -> Result<(), Box<dyn std::error::Error>> {
    let raw = std::fs::read_to_string(ctx.reports.join("registries.json"))?;
    let doc: serde_json::Value = serde_json::from_str(&raw)?;
    let items = registry(&doc, "minecraft:item")?;
    let components = registry(&doc, "minecraft:data_component_type")?;

    // Most items are blocks, and a block item is drawn as the block rather than
    // as a flat picture. Pairing them here saves a name lookup per drawn slot.
    let blocks_raw = std::fs::read_to_string(ctx.reports.join("blocks.json"))?;
    let blocks: serde_json::Map<String, serde_json::Value> = serde_json::from_str(&blocks_raw)?;
    let default_state = |name: &str| -> Option<u32> {
        let block = blocks.get(&format!("minecraft:{name}"))?;
        let states = block.get("states")?.as_array()?;
        let state = states
            .iter()
            .find(|s| s.get("default").and_then(|d| d.as_bool()).unwrap_or(false))
            .or_else(|| states.first())?;
        state.get("id")?.as_u64().map(|v| v as u32)
    };

    let mut out = String::with_capacity(96 * 1024);
    out.push_str(&format!(
        "//! Generated by neuton-datagen from Minecraft {} registries. Do not edit.\n\n",
        ctx.version
    ));
    out.push_str(
        "/// One item, by its protocol ID.\n\
         #[derive(Debug, Clone, Copy)]\n\
         pub struct Item {\n    \
             /// Registry name without the namespace, e.g. `oak_stairs`.\n    \
             pub name: &'static str,\n    \
             /// The block this item places, if it places one.\n    \
             pub block_state: Option<u32>,\n\
         }\n\n",
    );

    let mut with_blocks = 0usize;
    writeln!(out, "pub const ITEMS: &[Item] = &[")?;
    for name in &items {
        let state = default_state(name);
        if state.is_some() {
            with_blocks += 1;
        }
        match state {
            Some(id) => writeln!(out, "    Item {{ name: {name:?}, block_state: Some({id}) }},")?,
            None => writeln!(out, "    Item {{ name: {name:?}, block_state: None }},")?,
        }
    }
    writeln!(out, "];\n")?;

    writeln!(
        out,
        "/// Data component types, by protocol ID. What follows one on the wire\n\
         /// depends entirely on which it is, so reading a stack means knowing these."
    )?;
    writeln!(out, "pub const COMPONENTS: &[&str] = &[")?;
    for name in &components {
        writeln!(out, "    {name:?},")?;
    }
    writeln!(out, "];\n")?;

    out.push_str(
        "/// The item with this protocol ID, if there is one.\n\
         pub fn item(id: i32) -> Option<&'static Item> {\n    \
             usize::try_from(id).ok().and_then(|i| ITEMS.get(i))\n\
         }\n\n\
         /// The name of a data component type, for reading and for reporting\n\
         /// the ones this client does not yet know how to read.\n\
         pub fn component(id: i32) -> Option<&'static str> {\n    \
             usize::try_from(id).ok().and_then(|i| COMPONENTS.get(i)).copied()\n\
         }\n",
    );

    println!("  items         : {} ({with_blocks} place a block)", items.len());
    emit(&ctx.repo.join("crates/neuton-blocks/src/generated/items.rs"), &out)?;
    Ok(())
}
