//! Generates `neuton-protocol`'s packet ID tables from `reports/packets.json`.
//!
//! Packet IDs move between Minecraft versions with no warning, and a wrong ID
//! is a silent desync rather than a clean error. Taking them from the jar's own
//! report means they cannot drift.

use crate::{Ctx, const_name, emit};
use std::fmt::Write as _;

/// Order matters only for readability of the generated file.
const STATES: &[&str] = &["handshake", "status", "login", "configuration", "play"];
const DIRECTIONS: &[&str] = &["clientbound", "serverbound"];

pub fn generate(ctx: &Ctx) -> Result<(), Box<dyn std::error::Error>> {
    let raw = std::fs::read_to_string(ctx.reports.join("packets.json"))?;
    let doc: serde_json::Value = serde_json::from_str(&raw)?;

    let mut out = String::with_capacity(64 * 1024);
    writeln!(out, "// @generated by neuton-datagen from vanilla {} reports/packets.json", ctx.version)?;
    writeln!(out, "// Do not edit. Run `cargo run -p neuton-datagen` to regenerate.")?;
    writeln!(out, "#![allow(dead_code)]\n")?;
    writeln!(out, "/// Protocol number sent in the handshake.")?;
    writeln!(out, "pub const PROTOCOL_VERSION: i32 = {};", ctx.protocol)?;
    writeln!(out, "/// Human-readable version this build targets.")?;
    writeln!(out, "pub const GAME_VERSION: &str = {:?};\n", ctx.version)?;

    let mut total = 0usize;
    for state in STATES {
        let Some(dirs) = doc.get(*state) else { continue };
        writeln!(out, "pub mod {state} {{")?;
        for dir in DIRECTIONS {
            let Some(map) = dirs.get(*dir).and_then(|d| d.as_object()) else { continue };

            // Collect (id, name), sorted by id so the generated file reads like
            // the wire format rather than like a hash map.
            let mut entries: Vec<(i64, String)> = map
                .iter()
                .filter_map(|(k, v)| {
                    let id = v.get("protocol_id")?.as_i64()?;
                    Some((id, k.clone()))
                })
                .collect();
            entries.sort_by_key(|(id, _)| *id);
            total += entries.len();

            writeln!(out, "    /// {} packets sent {}.", entries.len(), described(dir))?;
            writeln!(out, "    pub mod {dir} {{")?;
            for (id, name) in &entries {
                writeln!(out, "        /// `{name}`")?;
                writeln!(out, "        pub const {}: i32 = {id};", const_name(name))?;
            }

            let max = entries.last().map(|(id, _)| *id).unwrap_or(-1);
            writeln!(out, "\n        /// Highest ID in this state/direction.")?;
            writeln!(out, "        pub const MAX_ID: i32 = {max};")?;
            writeln!(out, "        pub const COUNT: usize = {};", entries.len())?;

            // A dense name table for logging and packet dumps. Gaps become "".
            let len = (max + 1).max(0) as usize;
            let mut names = vec![""; len];
            for (id, name) in &entries {
                names[*id as usize] = name.as_str();
            }
            writeln!(out, "\n        /// Registry names indexed by protocol ID; `\"\"` marks an unused ID.")?;
            writeln!(out, "        pub static NAMES: [&str; {len}] = [")?;
            for chunk in names.chunks(4) {
                let line: Vec<String> = chunk.iter().map(|n| format!("{n:?}")).collect();
                writeln!(out, "            {},", line.join(", "))?;
            }
            writeln!(out, "        ];")?;
            writeln!(
                out,
                "
        /// Registry name for a protocol ID, or `None` if unassigned.
        #[inline]
        pub fn name(id: i32) -> Option<&'static str> {{
            let n = *NAMES.get(usize::try_from(id).ok()?)?;
            (!n.is_empty()).then_some(n)
        }}"
            )?;
            writeln!(out, "    }}\n")?;
        }
        writeln!(out, "}}\n")?;
    }

    let path = ctx.repo.join("crates/neuton-protocol/src/generated/ids.rs");
    emit(&path, &out)?;
    println!("  packet ids    : {total} across {} states", STATES.len());
    Ok(())
}

fn described(dir: &str) -> &'static str {
    match dir {
        "clientbound" => "server -> client",
        _ => "client -> server",
    }
}
