[package]
name = "neuton-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neuton-blocks = { workspace = true }
neuton-world = { path = "../neuton-world" }
bytemuck = { version = "1", features = ["derive"] }
neuton-assets = { version = "0.1.0", path = "../neuton-assets" }
wgpu = "30.0.1"
neuton-net = { version = "0.1.0", path = "../neuton-net" }

[dev-dependencies]
png = "0.18.1"
